stages:
  - build
  - test
  - deploy
  
build:
  image: docker
  services:
    - docker:dind  
  before_script:
    - docker info
    - docker-compose --version
  script:
    - apk add --no-cache docker-compose
    - docker build -t app -f app/Dockerfile .

test_job:
  stage: test
  image: python:latest
  script:
    - pip install pytest pytest-cov