version: '3.8'

services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: lappis
      MONGO_INITDB_ROOT_PASSWORD: lappis

  app:
    image: python:latest
    ports:
      - 8000:8000
    command: python src/main.py
    build:
      context: app
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - .:/app
